# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
since = 2020
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "üëçüèº"
subtitle = "–î–æ–∫—Ç–æ—Ä —ç–∫–æ–Ω–æ–º–∏—á–µ—Å–∫–∏—Ö –Ω–∞—É–∫, –ø—Ä–æ—Ñ–µ—Å—Å–æ—Ä –ë–§–£ –∏–º. –ö–∞–Ω—Ç–∞ –∏ –†–ê–ù–•–∏–ì–° , —Å–æ–≤–ª–∞–¥–µ–ª–µ—Ü –∏ –ø—Ä–µ–¥—Å–µ–¥–∞—Ç–µ–ª—å —Å–æ–≤–µ—Ç–∞ –¥–∏—Ä–µ–∫—Ç–æ—Ä–æ–≤ —Å–µ—Ç–∏ –º–∞–≥–∞–∑–∏–Ω–æ–≤ ¬´SPAR-–ö–∞–ª–∏–Ω–∏–Ω–≥—Ä–∞–¥¬ª"

[sidebar.avatar]
enabled = true
local = true
src = "img/ponomarev.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = false
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
